# -*- coding: utf-8 -*-
"""test_di_prova

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVzao5bblruR6fbQqGw3jzwygQ38sNwO
"""

# Rimuovi eventuali cartelle create parzialmente
!rm -rf Dyn-WNTR lorasim

# Clona LoRaSim
!git clone https://github.com/mcbor/lorasim.git

# Clona Dyn-WNTR forzando l'assenza di credenziali
!git -c core.askpass=true clone https://github.com/rastafaninplakeibol/Dyn-WNTR.git

!pip install -r /content/Dyn-WNTR/requirements.txt

"""### import estensione"""

import os

# Definiamo il percorso della cartella aml
aml_dir = "/content/Dyn-WNTR/mwntr/sim/aml"

if os.path.exists(aml_dir):
    print(f"📁 Contenuto di {aml_dir}:", os.listdir(aml_dir))

    # Se il file si chiama evaluator.py ma il codice cerca _evaluator, creiamo un alias
    if 'evaluator.py' in os.listdir(aml_dir) and '_evaluator.py' not in os.listdir(aml_dir):
        print("🔧 Rilevata discrepanza nel nome di evaluator. Creazione alias...")
        with open(os.path.join(aml_dir, '_evaluator.py'), 'w') as f:
            f.write("from .evaluator import *")
else:
    print("❌ La cartella 'aml' non è stata trovata nel percorso previsto.")

import sys
import os
import importlib

# Assicuriamoci che la root sia nel path
root_path = "/content/Dyn-WNTR"
if root_path not in sys.path:
    sys.path.insert(0, root_path)

importlib.invalidate_caches()

try:
    # Importiamo mwntr e verifichiamo i componenti chiave
    import mwntr
    from mwntr.sim.network_isolation import _network_isolation

    # Se la tua simulazione richiede il simulatore interattivo:
    from mwntr.sim.hydraulics import MWNTRInteractiveSimulator

    print("🚀 VITTORIA DEFINITIVA! Tutti i moduli, inclusi AML ed Evaluator, sono pronti.")
    print("Ora puoi inizializzare il modello con: wn = mwntr.network.WaterNetworkModel('NET_4.inp')")

except ImportError as e:
    print(f"❌ Errore di importazione specifico: {e}")
    # Visualizziamo dove Python sta effettivamente cercando il modulo
    import mwntr
    print(f"📍 MWNTR individuato in: {mwntr.__file__}")
except Exception as e:
    print(f"❌ Errore imprevisto: {e}")

"""patch per salvare correttamente i dati"""

import os
import importlib
import mwntr.sim.hydraulics

path_to_fix = '/content/Dyn-WNTR/mwntr/sim/hydraulics.py'

# Leggiamo il file riga per riga per identificare l'esatta indentazione
with open(path_to_fix, 'r') as f:
    lines = f.readlines()

new_lines = []
for line in lines:
    # Cerchiamo la riga incriminata
    if "node_res[key] = pd.DataFrame(data=np.array([node_res[key][name] for name in node_names]).transpose(), index=results.time," in line:
        # Ricaviamo l'indentazione originale della riga
        indent = line[:line.find("node_res[key]")]

        # Sostituiamo con un blocco Try/Except indentato correttamente
        patch = [
            f"{indent}try:\n",
            f"{indent}    _data = np.array([node_res[key][name] for name in node_names]).transpose()\n",
            f"{indent}    if _data.size == 0:\n",
            f"{indent}        node_res[key] = pd.DataFrame()\n",
            f"{indent}    else:\n",
            f"{indent}        node_res[key] = pd.DataFrame(data=_data, index=results.time, columns=node_names)\n",
            f"{indent}except Exception:\n",
            f"{indent}    node_res[key] = pd.DataFrame()\n"
        ]
        new_lines.extend(patch)
    elif "columns=node_names)" in line and "pd.DataFrame" not in line:
        # Saltiamo la riga orfana della vecchia chiamata a più righe
        continue
    else:
        new_lines.append(line)

with open(path_to_fix, 'w') as f:
    f.writelines(new_lines)

# Ricarichiamo il modulo
importlib.reload(mwntr.sim.hydraulics)
print("✅ Patch applicata con successo e modulo ricaricato!")

"""import rete"""

import mwntr
import matplotlib.pyplot as plt

# Percorso del file individuato
inp_file = '/content/Dyn-WNTR/NET_4.inp'

# Carichiamo il modello
wn = mwntr.network.WaterNetworkModel(inp_file)

print(f"Rete: {inp_file}")
print(f"Nodi: {wn.num_nodes}, Archi: {wn.num_links}")

"""### Import estensione lorasim

---


"""

# Installa SimPy (il motore su cui si basa LoRaSim)
!pip install simpy

# Clona la repository ufficiale nel tuo ambiente di lavoro
!git clone https://github.com/mcbor/lorasim.git

import sys
import os

# Aggiungiamo la cartella appena scaricata al PATH di Python
percorso_lorasim = '/content/lorasim' # Modifica se non sei su Colab
if percorso_lorasim not in sys.path:
    sys.path.append(percorso_lorasim)

# Ora possiamo importare le funzioni del simulatore!
import simpy
import lorasim

"""*testo in corsivo*## implementazione con gestione altezze e diverse grandezze"""

import random
import mwntr
import matplotlib.pyplot as plt

import random

def inserisci_serbatoi_con_valvole_iot(wn, n_serbatoi=5):
    junctions = wn.junction_name_list
    target_nodes = random.sample(junctions, n_serbatoi)

    taglie = {
        'Small':  {'tank_dia': 5.0,  'pipe_dia': 0.15},
        'Medium': {'tank_dia': 15.0, 'pipe_dia': 0.30},
        'Large':  {'tank_dia': 40.0, 'pipe_dia': 0.60}
    }
    taglia_nomi = list(taglie.keys())

    # Teniamo traccia delle valvole IoT inserite per passarla all'Agente
    valvole_iot_create = []

    for i, junc_name in enumerate(target_nodes):
        junc_node = wn.get_node(junc_name)
        taglia_scelta = random.choice(taglia_nomi)
        info = taglie[taglia_scelta]

        offset_altezza = random.uniform(30, 60) # Quote più alte per evitare pressioni negative
        new_tank_name = f"Tank_{taglia_scelta}_{i+1}"

        # Rinominato per riflettere il suo nuovo ruolo di attuatore
        new_valve_name = f"IoT_Valve_Tank_{i+1}"

        # 1. Aggiunta Tank
        wn.add_tank(new_tank_name,
                    elevation=junc_node.elevation + offset_altezza,
                    init_level=12.0, # Partiamo con i serbatoi pieni
                    min_level=0.0,
                    max_level=12.0,
                    diameter=info['tank_dia'],
                    coordinates=(junc_node.coordinates[0]+300, junc_node.coordinates[1]+300))

        # 2. Aggiunta Tubo/Valvola
        wn.add_pipe(new_valve_name,
                    start_node_name=junc_name,
                    end_node_name=new_tank_name,
                    length=30.0,
                    diameter=info['pipe_dia'],
                    roughness=110,
                    # FORZIAMO LO STATO INIZIALE A "CHIUSO" O "APERTO"
                    initial_status=mwntr.network.LinkStatus.Closed)

        valvole_iot_create.append(new_valve_name)

        print(f"✅ Attuatore IoT installato: {new_valve_name} (Collega {junc_name} a {new_tank_name})")

    return valvole_iot_create

# --- Reset Rete e Applicazione Asset IoT ---

# 1. Caricamento del modello originale
wn = mwntr.network.WaterNetworkModel('/content/Dyn-WNTR/NET_4.inp')

# 2. Rimozione dei serbatoi preesistenti (per testare solo la tua nuova strategia)
original_tanks = list(wn.tank_name_list)
for t_name in original_tanks:
    for l_name in wn.get_links_for_node(t_name):
        wn.remove_link(l_name)
    wn.remove_node(t_name)

# 3. Applicazione dei nuovi serbatoi con valvole IoT
# Salviamo la lista delle valvole restituita dalla funzione
lista_valvole_iot = inserisci_serbatoi_con_valvole_iot(wn, n_serbatoi=8)

# Verifica dei nuovi asset
print(f"\n📡 Configurazione completata con {len(lista_valvole_iot)} attuatori IoT pronti per il controllo remoto.")
print(f"Lista attuatori: {lista_valvole_iot}")

# Pattern calo fonte
wn.add_pattern('Calo_Fonte', [1,1,1,1,1,1, 0.8, 0.6, 0.4, 0.2, 0.1, 0.1, 0.1, 0.1])
res = wn.get_node('83')
res.head_pattern_name = 'Calo_Fonte'

wn.options.time.duration = 24 * 3600
wn.options.time.report_timestep = 3600

sim = mwntr.sim.WNTRSimulator(wn)
results = sim.run_sim()

"""### Agente"""

class AgenteAdattivo:
    def __init__(self, lista_valvole, soglia_critica=20.0):
        self.soglia_critica = soglia_critica
        self.lista_valvole = lista_valvole

        # Stato iniziale: Pressione ottima, Valvole chiuse, Intervallo lungo (Risparmio Rete)
        self.stato_percepito = {
            v: {'pressione': 50.0, 'timestamp': 0.0, 'tx_interval': 3600} for v in lista_valvole
        }
        self.stato_attuatori = {v: 'CLOSED' for v in lista_valvole}

    def elabora_uplink(self, pacchetti_ricevuti):
        """Aggiorna lo stato percepito con i pacchetti sopravvissuti alle collisioni"""
        for p in pacchetti_ricevuti:
            valvola_id = p['node_id']
            self.stato_percepito[valvola_id]['pressione'] = p['data']
            self.stato_percepito[valvola_id]['timestamp'] = p['timestamp']

    def calcola_intervallo_ottimale(self, pressione):
        """
        Funzione Obiettivo Semplificata:
        - Pressione Alta (Sicura) -> Trasmetti poco (es. 3600s / 1 ora) -> Meno Collisioni
        - Pressione in Calo (Attenzione) -> Trasmetti medio (es. 600s / 10 min)
        - Pressione Critica (Emergenza) -> Trasmetti tantissimo (es. 60s / 1 min) -> Rischio Collisioni, ma vitale.
        """
        if pressione > (self.soglia_critica + 20):  # Es: > 40m
            return 3600
        elif pressione > (self.soglia_critica + 5):   # Es: tra 25m e 40m
            return 600
        else:                                         # Es: < 25m (Crisi imminente o in corso)
            return 60

    def valuta_e_decidi(self, current_time):
        """Genera comandi fisici (Valvole) e comandi di rete (MAC commands per LoRa)"""
        comandi_downlink = {}

        for valvola_id, memoria in self.stato_percepito.items():
            pressione = memoria['pressione']
            stato_attuale = self.stato_attuatori[valvola_id]
            intervallo_attuale = memoria['tx_interval']

            # 1. OTTIMIZZAZIONE INTERVALLO (Ricalcolo dinamico)
            nuovo_intervallo = self.calcola_intervallo_ottimale(pressione)

            # Inizializziamo il dizionario dei comandi per questa valvola
            comandi_downlink[valvola_id] = {'azione_valvola': None, 'nuovo_tx': None}

            if nuovo_intervallo != intervallo_attuale:
                comandi_downlink[valvola_id]['nuovo_tx'] = nuovo_intervallo
                self.stato_percepito[valvola_id]['tx_interval'] = nuovo_intervallo
                print(f"📡 AGENTE: Riconfigurazione radio per {valvola_id}. Nuovo TX: {nuovo_intervallo}s")

            # 2. DECISIONE FISICA SULLA VALVOLA
            if pressione < self.soglia_critica and stato_attuale == 'CLOSED':
                comandi_downlink[valvola_id]['azione_valvola'] = 'OPEN'
                self.stato_attuatori[valvola_id] = 'OPEN'
                print(f"🧠 AGENTE [{current_time}s]: Crisi su {valvola_id}. Ordino: APERTURA.")

            elif pressione > (self.soglia_critica + 15) and stato_attuale == 'OPEN':
                comandi_downlink[valvola_id]['azione_valvola'] = 'CLOSED'
                self.stato_attuatori[valvola_id] = 'CLOSED'
                print(f"🧠 AGENTE [{current_time}s]: Rete stabile su {valvola_id}. Ordino: CHIUSURA.")

        return comandi_downlink

"""### rete LoRaWAN"""

import simpy
import random
import math

class LoRaWAN_Network:
    def __init__(self, lista_nodi_iot, tx_interval=600):
        self.env = simpy.Environment()
        self.gateway = Gateway(self.env)
        self.nodes = []
        self.tx_interval = tx_interval

        print("\n📡 INIZIALIZZAZIONE RETE LoRaWAN...")
        for i, node_id in enumerate(lista_nodi_iot):
            sf = random.choice([7, 8, 9, 10, 11, 12])
            node = SensorNode(self.env, node_id, self.gateway, sf, self.tx_interval)
            self.nodes.append(node)
            print(f"   [+] Sensore accoppiato a {node_id} (SF: {sf})")

    def run_communication_step(self, time_step):
        target_time = self.env.now + time_step
        self.env.run(until=target_time)
        return self.gateway.get_and_clear_buffer()

class Gateway:
    def __init__(self, env):
        self.env = env
        self.received_packets = []
        self.active_transmissions = []
        self.stat_totale_inviati = 0
        self.stat_totale_persi = 0

    def receive_uplink(self, packet, time_on_air):
        self.stat_totale_inviati += 1
        self.active_transmissions.append(packet)
        yield self.env.timeout(time_on_air)

        collision = len(self.active_transmissions) > 1
        if not collision:
            self.received_packets.append(packet)
        else:
            self.stat_totale_persi += 1

        self.active_transmissions.remove(packet)

    def get_packet_loss_rate(self):
        if self.stat_totale_inviati == 0:
            return 0.0
        return (self.stat_totale_persi / self.stat_totale_inviati) * 100.0

    def get_and_clear_buffer(self):
        data = self.received_packets.copy()
        self.received_packets.clear()
        return data

class SensorNode:
    def __init__(self, env, node_id, gateway, sf, tx_interval):
        self.env = env
        self.node_id = node_id
        self.gateway = gateway
        self.sf = sf
        self.tx_interval = tx_interval
        self.current_pressure = 0.0
        self.time_on_air = (2 ** sf) / 125000.0 * 20
        self.env.process(self.transmit_loop())

    def update_sensor_data(self, pressure):
        self.current_pressure = pressure

    def aggiorna_intervallo(self, nuovo_intervallo):
        if self.tx_interval != nuovo_intervallo:
            self.tx_interval = nuovo_intervallo

    def transmit_loop(self):
        yield self.env.timeout(random.uniform(0, self.tx_interval))
        while True:
            packet = {
                'node_id': self.node_id,
                'data': self.current_pressure,
                'timestamp': self.env.now
            }
            self.env.process(self.gateway.receive_uplink(packet, self.time_on_air))
            yield self.env.timeout(self.tx_interval)

"""### Simulazione"""

# --- SETUP INIZIALE ---
wn = mwntr.network.WaterNetworkModel('/content/Dyn-WNTR/NET_4.inp')

# ... (Lascia pure qui il codice di rimozione tank e applicazione valvole IoT che avevi) ...
original_tanks = list(wn.tank_name_list)
for t_name in original_tanks:
    for l_name in wn.get_links_for_node(t_name):
        wn.remove_link(l_name)
    wn.remove_node(t_name)

lista_valvole_iot = inserisci_serbatoi_con_valvole_iot(wn, n_serbatoi=8)

# Pattern calo fonte
wn.add_pattern('Calo_Fonte', [1,1,1,1,1,1, 0.8, 0.6, 0.4, 0.2, 0.1, 0.1, 0.1, 0.1])
res = wn.get_node('83')
res.head_pattern_name = 'Calo_Fonte'

# --- PARAMETRI CO-SIMULAZIONE ---
intervallo_trasmissione = 3600 # Partiamo con invii rari (1 ora)
lora_net = LoRaWAN_Network(lista_valvole_iot, tx_interval=intervallo_trasmissione)
agente = AgenteAdattivo(lista_valvole_iot, soglia_critica=20.0)

time_step = 600
wn.options.time.duration = 24 * 3600
wn.options.time.hydraulic_timestep = time_step # CRUCIALE PER LO STEP BY STEP
wn.options.time.report_timestep = time_step

wn.options.hydraulic.demand_model = 'PDA'
wn.options.hydraulic.minimum_pressure = 0.0
wn.options.hydraulic.required_pressure = 20.0

sim = mwntr.sim.WNTRSimulator(wn)

print("\n🚀 INIZIO CO-SIMULAZIONE CPS (Cyber-Physical System)...")

# --- IL VERO MASTER LOOP ---
for tempo_corrente in sim: # Usa il generatore di WNTR!

    # 1. I sensori leggono il dato reale di pressione (Head - Elevation)
    for nodo_lora in lora_net.nodes:
        tank_name = nodo_lora.node_id.replace("IoT_Valve_", "")
        # Troviamo il nodo a cui è attaccato il serbatoio per misurare la pressione di rete
        try:
            link_obj = wn.get_link(nodo_lora.node_id)
            junc_name = link_obj.start_node_name
            junc_obj = wn.get_node(junc_name)
            pressione_reale = junc_obj.head - junc_obj.elevation
            nodo_lora.update_sensor_data(pressione_reale)
        except AttributeError:
            pass # Salta se le altezze non sono ancora calcolate a T=0

    # 2. Telecomunicazioni (LoRaSim)
    pacchetti_sopravvissuti = lora_net.run_communication_step(time_step)

    # 3. Cervello (Agente di Controllo)
    agente.elabora_uplink(pacchetti_sopravvissuti)
    comandi = agente.valuta_e_decidi(tempo_corrente)

    # 4. Attuazione (Downlink)
    for valvola_id, comandi_specifici in comandi.items():
        nuovo_tx = comandi_specifici['nuovo_tx']
        if nuovo_tx is not None:
            for nodo in lora_net.nodes:
                if nodo.node_id == valvola_id:
                    nodo.aggiorna_intervallo(nuovo_tx)
                    break

        azione_valvola = comandi_specifici['azione_valvola']
        if azione_valvola is not None:
            valvola_mwntr = wn.get_link(valvola_id)
            if azione_valvola == 'OPEN':
                valvola_mwntr.status = mwntr.network.LinkStatus.Opened
            elif azione_valvola == 'CLOSED':
                valvola_mwntr.status = mwntr.network.LinkStatus.Closed

print("\n🏁 CO-SIMULAZIONE COMPLETATA.")
print(f"📊 Packet Loss Rate Finale: {lora_net.gateway.get_packet_loss_rate():.2f}%")